### ISSUE TITLE
Inconsistent "break" status between GUI and internal debugger

### ISSUE THREAD

**Issue by Colpocorto** [openMSX/debugger#173]
Steps to reproduce:

-Open any OpenMSX instance and a Debugger instance.
-Connect the Debugger UI to the OpenMSX instance
-Execute "debug break" at the OpenMSX console or click the "break" button. The debugger will get into "step-by-step" mode.
-Execute "debug cont" at the OpenMSX console. The debugger should exit the "step-by-step" mode but that never happens (the "break" button remains disabled and the "run" button remains enabled).

**Comment by pvmm** [comment]
This would require openMSX to tell directly to the debugger running/break state changes, just like it already does with breakpoint/watchpoint/conditions state updates. Do you find that useful in some way? Because I guess most people don't need to control running/break state from two different interfaces.

**Comment by Colpocorto** [comment]
> This would require openMSX to tell directly to the debugger running/break state changes, just like it already does with breakpoint/watchpoint/conditions state updates. Do you find that useful in any way? Because I guess most people don't need to control running/break state from two different interfaces. Since typing "debug cont" is more annoying than clicking a button.

But this feature used to work fine in the past! It must be some kind of regression introduced in the new releases.

**Comment by pvmm** [comment]
Created PR #178.
